import "react-datepicker/dist/react-datepicker.css";
import "@/assets/scss/main.scss";

export const metadata = {
  title: "CRM | Kataria",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
