import "react-datepicker/dist/react-datepicker.css";
import "@/assets/scss/main.scss";
import { Toaster } from "react-hot-toast";
import Providers from "@/provider/ReduxProviders";

export const metadata = {
  title: "CRM | Kataria",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster
          position="top-right"
          toastOptions={{
            duration: 4000,
            style: {
              fontSize: 18,
              padding: 12,
              minWidth: "200px",
            },
          }}
          reverseOrder={false}
        />
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
